### PR TITLE
Stereoscopic / Suppress warning / "msrc" param

### PR DESCRIPTION
**Pull request by gtk2k**
## #Stereoscopic source support

Stereoscopic source use set 'src' and 'stereoscopicType'.
stereoscopicType value
'OU':Left eye:Over  / Right eye:Under.
'UO':Left eye:Under / Right eye:Over.
'LR':Left eye:Left  / Right eye:Right.
'RL':Left eye:Right / Right eye:Left.
### Image demo

[Page](https://gtk2k.github.io/aframe_stereoscopic_warning_fix/aframe_image_lr.html)
[Code](https://github.com/gtk2k/gtk2k.github.io/blob/master/aframe_stereoscopic_warning_fix/aframe_image_lr.html)
### Video demo

[Page](https://gtk2k.github.io/aframe_stereoscopic_warning_fix/aframe_video_2560x720_rl.html)
[Code](https://github.com/gtk2k/gtk2k.github.io/blob/master/aframe_stereoscopic_warning_fix/aframe_video_2560x720_rl.html)
### Videosphere demo

[Page](https://gtk2k.github.io/aframe_stereoscopic_warning_fix/aframe_videosphere_1920x960_rl.html)
[Code](https://github.com/gtk2k/gtk2k.github.io/blob/master/aframe_stereoscopic_warning_fix/aframe_videosphere_1920x960_rl.html)
## #Suppress warning

Suppress texture source loading time warning. (But, incomplete. ex. loop play)
ch_texturesize_warning
ff_texturesize_warning
Compare demo
[Unfixed](https://gtk2k.github.io/aframe_stereoscopic/aframe_videosphere_1280x640_lr.html)
[Fixed](https://gtk2k.github.io/aframe_stereoscopic_warning_fix/aframe_videosphere_1280x640_lr.html)
## #"msrc" param

Material component add "msrc" param.
This is mobile source.
[Page](https://gtk2k.github.io/src_switch/aframe_videosphere_src_switch_test.html)
[Code](https://github.com/gtk2k/gtk2k.github.io/blob/master/src_switch/aframe_videosphere_src_switch_test.html)

### CODE REVIEW

**Comment by dmarcos** [comment]
Thanks! VREffect is an external dependency and we should not modify it. If we need to change it we should do a PR against the three.js repo. Is there a way to implement this without touching VREffect?

**Comment by gtk2k** [comment]
>Is there a way to implement this without touching VREffect?

Sorry, I have no idea.

I think this is best way. 
There are other ways, but in any case VREffect need to modify.

**Comment by gtk2k** [comment]
>Is there a way to implement this without touching VREffect?

I thought way to withuout touch VREffect.

in a-scene.js
```js
var self = this;
renderer.orgSetViewport = renderer.setViewport;
renderer.setViewport = function (left, top, width, height) {
  if (left === 0) {
    self.leftPreprocess();
  } else {
    self.rightPreprocess();
  }
  renderer.orgSetViewport(left, top, width, height);
};
```

**Comment by ngokevin** [comment]
Are you updating this PR to do it without modifying VREffect?

**Comment by gtk2k** [comment]
Sorry for the late reply.
This PR close and I will  without touching VREffect PR later.

**Comment by ngokevin** [comment]
Is there any update on further work for this? There has been some demand for more stereoscopicness.

**Comment by oscarmarinmiro** [comment]
Hi there and congrats on Aframe, it's awesome!

I just wrote a component to make stereo in general available to AFrame. It builds on the 'layer' concept of THREE.js (mentioned in this issue: https://github.com/mrdoob/three.js/issues/6437). You can simply add a new property called 'stereo' to an entity, specifying if that entity is going for the 'left' or 'right' eye on VR mode (which translates to layer 1 or 2). Also if it has been applied to a sphere (videospheres dont pull video assets right in my dev (?)) it internally maps half of the video texture. Also there's a 'half-dome' option for video. I needed it for my devs and thought would be useful to share. It also adds a 'click' event to the canvas, so the video can be played on mobile devices.

The component is hosted here:
https://github.com/oscarmarinmiro/aframe-stereo-component

Demo examples here:
http://oscarmarinmiro.github.io/aframe-stereo-component/

Thanks for all your hard work and apologies in advance for my english (not my primary language) and my code (first timer with aframe components)

The component is hosted here:

**Comment by ngokevin** [comment]
Great work, I LOVE IT! Your English is great, and you can always talk to@dmarcos in Spanish :)

Are you on our Slack channel: https://aframevr-slack.herokuapp.com/ ?

**Pull request closed without merging**
