### PR TITLE
SphereBufferGeometry instead of SphereGeometry.

### PR DESCRIPTION
**Pull request by mrdoob**

### CODE REVIEW

**Comment by jcarpenter** [comment]
PR from Doob. We're big time now ;)

Are there any differences to texturing, animation and-or lighting behavior with buffer geometry versus standard geometries? IIRC you're fine with buffer so long as you're not manipulating vertices?

**Comment by ngokevin** [comment]
Thanks! Yeah we have an issue to switch to buffer geometries for the basic geometry component

**Comment by ngokevin** [comment]
I think tests need addressing. npm run test

**Comment by mrdoob** [comment]
> Are there any differences to texturing, animation and-or lighting behavior with buffer geometry versus standard geometries? IIRC you're fine with buffer so long as we're not manipulating vertices?

Yeah. As far as I understand you're not modifying vertices? 

Internally `SphereGeometry` creates a `SphereBufferGeometry` and converts to `Geometry`:

https://github.com/mrdoob/three.js/blob/dev/src/extras/geometries/SphereGeometry.js#L21

> Thanks! Yeah we have an issue to switch to buffer geometries for the basic geometry component. Possibly for all the geometry primitives

Oh, I changed it because I noticed you're already using `PlaneBufferGeometry`.

**Comment by ngokevin** [comment]
thanks! i can get the tests up while we get travis hooked on

**Pull request merged**
