### PR TITLE
oscillate behavior #15

### PR DESCRIPTION
**Pull request by nickdesaulniers**
review? @dmarcos 

merge conflicts I'll fix up real quick

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
maybe I should differentiate between position and orientation, so we can oscillate orientations as well?

**Comment by dmarcos** [comment]
I don’t like the animations as a child because:
1. You cannot reuse an animation for multiple objects. You will have one rAF per animation instance.  the 2. updates won’t be properly coordinated with the main animation loop of the scene,

What about this? Define animations as a core element vr-animation loaded as an asset. They have an update function called from the main rAF. The scene will have a list of all animations and will call update on them per frame. vr-objects will have an attribute animation with an animation id. When setting the attribute we can call a method on the animation addObject(object). When the main rAF calls update on the animations, each animation will iterate over the objects attached to it updating whatever they need to update.

**Comment by jcarpenter** [comment]
Let's use this week to dig into animation approaches more deeply. For now I can use nick's approach. It gives me the ability to define re-usable animations with per-instance attributes, which is what I need for Tuesday.

**Comment by jcarpenter** [comment]
Captured some thoughts in issue #15

**Comment by jcarpenter** [comment]
@nickdesaulniers I had a chance to kick the tires on the Oscillate tag and it works well. On Monday let's discuss a more generic solution; perhaps along the lines of what I propose in #15. If you stub out a generic component for "move", based on tween.js, I can then take that an create a library of animation components.

**Pull request closed without merging**
