### PR TITLE
Add loader support for .OBJ + .MTL assets.

### PR DESCRIPTION
**Pull request by donmccurdy**
See: https://github.com/aframevr/awesome-aframe/pull/7

I've written a separate [obj-loader](https://github.com/donmccurdy/aframe-obj-loader-component) component for this same .OBJ+.MTL support, but am opening this in case it's worth discussing merging into aframe-core. Example code:

``` html
<a-entity loader="src: url(./tree.obj);
                  mtl: url(./tree.mtl);">
</a-entity>
```

There are a couple difficulties with merging:
1. No way to asynchronously load OBJMTLLoader and MTLLoader yet.
2. A .MTL file can't easily be used with the material component, because a single .MTL file may generate more than one THREE.Mesh_<Type>_Material instances. Possibly unintuitive for new users.

Interested to hear your thoughts (and how best to handle any other new asset formats).

---

_Note:_ Another option might be to create a new component (e.g. `material-mtl`) to load the .MTL file and apply it to the model, which makes it more clear that `material` vs `material-mtl` components are mutually exclusive. We'd need to customize THREE.OBJLoader for that though – it doesn't currently preserve enough metadata to map each material from the .MTL to the correct parts of the model.

### CODE REVIEW

**Comment by ngokevin** [comment]
Thanks for the PR! Will try to get to this later.

Initial notes is that we plan to require the THREE modules directly from the three dep. Will think more about how to handle multiple meshes and whether to split out into another component.

**Comment by dmarcos** [comment]
The patch looks good! Do you think we should get rid of the ```loader``` component and add a ```src``` property to the ```geometry``` and ```material``` components. One would do:

````html
<a-entity geometry="src: url(./tree.obj);
               material="src: url(./tree.mtl);">
</a-entity>
````
@ngokevin What do you suggest to handle the new THREE modules. Should people do a PR on your THREE-dev repo?

**Comment by donmccurdy** [comment]
@dmarcos adding a `src` property to the `material` component might be tricky, since a `.mtl` file can contain and apply multiple material definitions. They're mapped by name to different parts of the `.obj` model, which also requires loading the `.obj` with that in mind – OBJMTLLoader does this, and OBJLoader does not, but there's probably no harm in always loading a `.obj` as if it were going to have a `.mtl` file applied.

Having separate `loader` components does seem a little weird to me, but wouldn't it be difficult for users to add support for a new format (e.g. gLTF) if it's not exposed as a component you can override? The extensibility is nice.

**Comment by ngokevin** [comment]
I like having model geometry and material components separate from our basic polygon geometry and materials. For now, having everything just in `loader` seems okay to me. Although I do want to rename it to `model`.

THREE modules not in THREE we can keep in `vendor/`. If they're on NPM, then we can pull from NPM.

Let me take a look.

**Comment by ngokevin** [comment]
@donmccurdy Would you mind adding an example? You could maybe modify the current `model` example, adding a second model that uses an MTL file?

**Comment by donmccurdy** [comment]
Sure thing, yeah. Added a crate model – I assume anything free for personal/commercial use is ok?

**Comment by cvan** [comment]
> Sure thing, yeah. Added a crate model – I assume anything free for personal/commercial use is ok?

yep - just if you could credit the source, that'd be great

**Comment by donmccurdy** [comment]
Attribution in models/crate/README.md.

**Comment by ngokevin** [comment]
@dmarcos looks good to me. want to merge?

screen shot 2016-01-07 at 11 23 09 am

**Comment by ngokevin** [comment]
Re-pinging @dmarcos

**Comment by dmarcos** [comment]
Nice! Thanks @donmccurdy

**Comment by cvan** [comment]
we should probably document somewhere in the docs the support for OBJ/COLLADA/gLTF internally in aframe-core, which things already have third-party components, and which things are upcoming.

https://aframe.io/docs/primitives/a-model.html
https://aframe.io/docs/components/loader.html

**Pull request merged**
