### PR TITLE
alias primitive: cube to primitive: box

### PR DESCRIPTION
**Pull request by ngokevin**
this has bit me several times when i accidentally type cube

### CODE REVIEW

**Comment by fernandojsg** [comment]
I don't really like to use an alias for something that is already there and understandable like ```box```, also  people may think that a ```cube``` will be just a box with the same size for ```width/height/depth``` (in that case I think it could be useful)

**Comment by ngokevin** [comment]
i know about box and i find myself typing cube so many times because we call them cube in all of our basic examples and primitives. sort of consistent with three.js as well.

alternatively we could set a warning. for API design aliasing is not great, but designing for humans it's good to have some room for input error.

**Comment by fernandojsg** [comment]
```sort of consistent with three.js as well.``` in fact three.js deprecated ```THREE.CubeGeometry``` and they just implemented ```THREE.BoxGeometry``` for the same reason. They currently give you a warning if you use it, so probably I'll also use a warning, or even just use ```THREE.CubeGeometry``` when you write ```primitive: cube``` so when it will be really deprecated on three.js you'll also get notified, anyway I still don't believe that including an already "soon to be deprecated" could be a good idea.
Like I said I'm not a big fan of simple alias that doesn't add any meaningful. If I see that there's just a cube primitive, I could think that it's acting like a simple box, but If I see that I can use cube and box, I'll think that cube will have the same size for w/h/d.

**Comment by dmarcos** [comment]
Box is a more accurate description of the geometry than cube. Cube implies 6 faces of the same size.

**Comment by ngokevin** [comment]
I understand the difference between box and cube, that's kindergarten. Though it's not little value if I've accidentally typed cube several times as a typo and have wondered why nothing has was rendering. 

Anyways, I'll just go with the warning.

**Comment by dmarcos** [comment]
I apologize, I'm not trying to explain the difference between ```cube``` and ```box```. I was just trying to reason about why the word ```cube``` is not appropriate to refer to the primitive we expose under ```box```.  Other engines seem to follow the same naming convention:
Playcanvas - https://github.com/playcanvas/engine/blob/master/examples/spinning_cube/index.html#L28
Turbulenz - https://github.com/turbulenz/turbulenz_engine/blob/master/samples/tsscripts/templates/physics.ts#L237
GooJS - https://github.com/GooTechnologies/goojs/blob/master/examples/goo/entities/components/MeshRendererComponent/MeshRendererComponent-example.js#L65

**Comment by ngokevin** [comment]
np, i think the warning is more sensible. updated

**Pull request merged**
